### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by h2oboycoder** [hakimov-dev/To-Do-App#1]
Please Add A Checkbox Field For Better Understanding 
:)

**Comment by h2oboycoder** [comment]
Sorry! Wrong Repo!

**Comment by h2oboycoder** [comment]
Sorry!

**Comment by hakimov-dev** [comment]
> Please Add A Checkbox Field For Better Understanding :)

**Comment by hakimov-dev** [comment]
> Please Add A Checkbox Field For Better Understanding :)

Ok, maybe later. I will add that.
